/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.tetrabox.MiniJavaRuntimeModule
import org.tetrabox.MiniJavaStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MiniJavaIdeSetup extends MiniJavaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MiniJavaRuntimeModule, new MiniJavaIdeModule))
	}
	
}
