/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modifiers</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tetrabox.miniJava.Modifiers#getType <em>Type</em>}</li>
 *   <li>{@link org.tetrabox.miniJava.Modifiers#getDeclarator <em>Declarator</em>}</li>
 *   <li>{@link org.tetrabox.miniJava.Modifiers#getThrows <em>Throws</em>}</li>
 * </ul>
 *
 * @see org.tetrabox.miniJava.MiniJavaPackage#getModifiers()
 * @model
 * @generated
 */
public interface Modifiers extends FieldDeclaration, MethodHeader
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.tetrabox.miniJava.MiniJavaPackage#getModifiers_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.tetrabox.miniJava.Modifiers#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Declarator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declarator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarator</em>' attribute.
   * @see #setDeclarator(String)
   * @see org.tetrabox.miniJava.MiniJavaPackage#getModifiers_Declarator()
   * @model
   * @generated
   */
  String getDeclarator();

  /**
   * Sets the value of the '{@link org.tetrabox.miniJava.Modifiers#getDeclarator <em>Declarator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declarator</em>' attribute.
   * @see #getDeclarator()
   * @generated
   */
  void setDeclarator(String value);

  /**
   * Returns the value of the '<em><b>Throws</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Throws</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Throws</em>' attribute.
   * @see #setThrows(String)
   * @see org.tetrabox.miniJava.MiniJavaPackage#getModifiers_Throws()
   * @model
   * @generated
   */
  String getThrows();

  /**
   * Sets the value of the '{@link org.tetrabox.miniJava.Modifiers#getThrows <em>Throws</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Throws</em>' attribute.
   * @see #getThrows()
   * @generated
   */
  void setThrows(String value);

} // Modifiers
