/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prefix Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.tetrabox.miniJava.MiniJavaPackage#getPrefixExpression()
 * @model
 * @generated
 */
public interface PrefixExpression extends EObject
{
} // PrefixExpression
