/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tetrabox.miniJava.Primary#getSuffixes <em>Suffixes</em>}</li>
 * </ul>
 *
 * @see org.tetrabox.miniJava.MiniJavaPackage#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends PostfixExpression
{
  /**
   * Returns the value of the '<em><b>Suffixes</b></em>' containment reference list.
   * The list contents are of type {@link org.tetrabox.miniJava.Suffix}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Suffixes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suffixes</em>' containment reference list.
   * @see org.tetrabox.miniJava.MiniJavaPackage#getPrimary_Suffixes()
   * @model containment="true"
   * @generated
   */
  EList<Suffix> getSuffixes();

} // Primary
