/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.tetrabox.miniJava.MiniJavaPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends BlockStatement
{
} // Statement
