/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.tetrabox.miniJava.MiniJavaPackage#getStatementExpression()
 * @model
 * @generated
 */
public interface StatementExpression extends EObject
{
} // StatementExpression
