/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declarators</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tetrabox.miniJava.VariableDeclarators#getVariableDeclarators <em>Variable Declarators</em>}</li>
 * </ul>
 *
 * @see org.tetrabox.miniJava.MiniJavaPackage#getVariableDeclarators()
 * @model
 * @generated
 */
public interface VariableDeclarators extends LocalVariableDeclaration
{
  /**
   * Returns the value of the '<em><b>Variable Declarators</b></em>' containment reference list.
   * The list contents are of type {@link org.tetrabox.miniJava.VariableDeclarator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Declarators</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Declarators</em>' containment reference list.
   * @see org.tetrabox.miniJava.MiniJavaPackage#getVariableDeclarators_VariableDeclarators()
   * @model containment="true"
   * @generated
   */
  EList<VariableDeclarator> getVariableDeclarators();

} // VariableDeclarators
