/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.tetrabox.minijava.ui.internal.MinijavaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MiniJavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MinijavaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MinijavaActivator.getInstance().getInjector(MinijavaActivator.ORG_TETRABOX_MINIJAVA);
	}
	
}
