/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.minijava.semantics.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.tetrabox.minijava.xtext.miniJava.Program
import org.tetrabox.minijava.xtext.tests.MiniJavaInjectorProvider

import static extension org.tetrabox.minijava.semantics.ProgramAspect.*

@RunWith(XtextRunner)
@InjectWith(MiniJavaInjectorProvider)
class MiniJavaSemanticsTest {
	@Inject
	ParseHelper<Program> parseHelper



	@Test
	def void longModel() {
		val Program result = parseHelper.parse('''class A {
		
		}
		
		class B extends A{
		
			int x;
		}
		
		class Pair {
		
			int fst;
			int snd;  
			
			int other() {
				return 1;
			}
			
			Pair do() {
				return this;
			}
			
			A test(B i) {
				return (A)i;
			// return new B(1);
			}
		
		    Pair setfst(int newfst, String s)  {
				return new Pair(newfst, this.snd);
			}
			
		    Pair setsnd(int newscd){
				return new Pair(this.fst, newscd);
			}
		}
		
		//Test
		//new Pair(1, 2).setfst(1,"")
		new Pair(1,2).test(   (B) new A() )      ''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)

		result.execute
	}
	
	
	
	
	
	
	@Test
	def void test3() {
		val Program result = parseHelper.parse('''
				
		class B {
			int x;
		}
		
		class Pair {
		
			int fst;
			int snd;
			B b;
			
		}
		
		new Pair(12,56,new B(2)) ''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)

		result.execute
	}

}
