<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="minijavadynamicdata" nsURI="http://org.tetrabox.minijava.xminijavamt/minijavadynamicdata/" nsPrefix="minijavadynamicdata">
    <eClassifiers xsi:type="ecore:EClass" name="Context">
      <eOperations name="createChildContext" eType="/0/Context">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="findBinding" eType="/0/SymbolBinding">
        <eAnnotations source="aspect"/>
        <eParameters name="symbol" eType="/0/Symbol"/>
      </eOperations>
      <eOperations name="findCurrentContext" eType="/0/Context">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1" eType="/0/SymbolBinding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentContext" eType="/0/Context" eOpposite="/0/Context/childContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="childContext" eType="/0/Context" containment="true" eOpposite="/0/Context/parentContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value">
      <eOperations name="customToString">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="copy" eType="/0/Value">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="/0/Value">
      <eOperations name="copy" eType="/0/Value">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="customToString">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fieldbindings" upperBound="-1" eType="/0/FieldBinding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="/1/Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SymbolBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="/0/Value" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="/0/Symbol"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="/1/Field"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="/0/Value" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="/0/Value">
      <eOperations name="copy" eType="/0/Value">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="customToString">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="/0/Value">
      <eOperations name="customToString">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="copy" eType="/0/Value">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutputStream">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stream" unique="false" upperBound="-1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RefValue" eSuperTypes="/0/Value">
      <eOperations name="copy" eType="/0/Value">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="customToString">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="/0/Instance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eOperations name="findCurrentFrame" eType="/0/Frame">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="findCurrentContext" eType="/0/Context">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="println">
        <eAnnotations source="aspect"/>
        <eParameters name="string">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations name="pushNewContext">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="popCurrentContext">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="pushNewFrame">
        <eAnnotations source="aspect"/>
        <eParameters name="receiver" eType="/0/Instance"/>
        <eParameters name="c" eType="/0/Call"/>
        <eParameters name="newContext" eType="/0/Context"/>
      </eOperations>
      <eOperations name="popCurrentFrame">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootFrame" eType="/0/Frame" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="heap" upperBound="-1" eType="/0/Instance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputStream" eType="/0/OutputStream" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Frame">
      <eOperations name="findCurrentFrame" eType="/0/Frame">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="findCurrentContext" eType="/0/Context">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="/0/Call" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="/0/Instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="childFrame" eType="/0/Frame" containment="true" eOpposite="/0/Frame/parentFrame"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentFrame" eType="/0/Frame" eOpposite="/0/Frame/childFrame"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootContext" eType="/0/Context" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" eType="/0/Value" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NullValue" eSuperTypes="/0/Value"/>
    <eClassifiers xsi:type="ecore:EClass" name="Call"/>
    <eClassifiers xsi:type="ecore:EClass" name="NewCall" eSuperTypes="/0/Call">
      <eStructuralFeatures xsi:type="ecore:EReference" name="new" eType="/1/New"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodCall2" eSuperTypes="/0/Call">
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodcall" eType="/1/MethodCall"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Symbol">
      <eAnnotations source="aspect"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="miniJava" nsURI="http://org.tetrabox.minijava.xminijavamt/miniJava/" nsPrefix="miniJava">
    <eClassifiers xsi:type="ecore:EClass" name="Program">
      <eOperations name="execute" eType="/1/State">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1" eType="/1/Import" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1" eType="/1/TypeDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Import">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" eSuperTypes="/1/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessLevel" eType="/1/AccessLevel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implements" unique="false" upperBound="-1" eType="/1/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1" eType="/1/Member" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="/1/TypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="/1/Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="/1/TypeDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="Member" eSuperTypes="/1/TypedDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="/1/AccessLevel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="/1/Member">
      <eOperations name="findOverride" eType="/1/Method">
        <eAnnotations source="aspect"/>
        <eParameters name="c" eType="/1/Class"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1" eType="/1/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="/1/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="/1/Symbol">
      <eOperations name="compare">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="other" eType="/1/Parameter"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="/1/Member">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="/1/Statement /1/Assignee">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eOperations name="fakeMain">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AccessLevel">
      <eLiterals name="PRIVATE" literal="private"/>
      <eLiterals name="PROTECTED" value="1" literal="protected"/>
      <eLiterals name="PUBLIC" value="2" literal="public"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="/1/Statement">
      <eOperations name="evaluateStatementKeepContext">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Statement">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrintStatement" eSuperTypes="/1/Statement">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="/1/Statement">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="/1/Statement">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenBlock" eType="/1/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="/1/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="/1/Statement">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="/1/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="/1/Statement">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="/1/Assignment" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="progression" eType="/1/Assignment" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="/1/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeRef">
      <eOperations name="compare">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="other" eType="/1/TypeRef"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleTypeRef" eSuperTypes="/1/TypeRef"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassRef" eSuperTypes="/1/SingleTypeRef">
      <eOperations name="compare">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="other" eType="/1/TypeRef"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedClass" eType="/1/TypeDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedDeclaration" eSuperTypes="/1/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="/1/TypeRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="/1/TypedDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="/1/Symbol /1/Assignee"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="/1/Statement">
      <eOperations name="evaluateStatement">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="/1/Assignee" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assignee"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeRef" eSuperTypes="/1/TypeRef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="/1/SingleTypeRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerTypeRef" eSuperTypes="/1/SingleTypeRef"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanTypeRef" eSuperTypes="/1/SingleTypeRef"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringTypeRef" eSuperTypes="/1/SingleTypeRef"/>
    <eClassifiers xsi:type="ecore:EClass" name="VoidTypeRef" eSuperTypes="/1/SingleTypeRef"/>
    <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Equality" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Inequality" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperiorOrEqual" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InferiorOrEqual" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Superior" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Inferior" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Neg" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccess" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="/1/Field"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodCall" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="/1/Method"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringConstant" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntConstant" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BoolConstant" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="This" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Super" eSuperTypes="/1/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Null" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="New" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="/1/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SymbolRef" eSuperTypes="/1/Expression">
      <eOperations name="evaluateExpression" eType="/1/Value">
        <eAnnotations source="aspect"/>
        <eParameters name="state" eType="/1/State"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="/1/Symbol"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eAnnotations source="aspect"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value">
      <eAnnotations source="aspect"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
