/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.minijava.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.tetrabox.minijava.xtext.ui.internal.SmalljavaActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MiniJavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmalljavaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmalljavaActivator.getInstance().getInjector(SmalljavaActivator.ORG_EXAMPLE_SMALLJAVA_SMALLJAVA);
	}
	
}
