/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.tetrabox.miniJava.MiniJavaPackage;
import org.tetrabox.miniJava.Suffix;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Suffix</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SuffixImpl extends MinimalEObjectImpl.Container implements Suffix
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuffixImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MiniJavaPackage.Literals.SUFFIX;
  }

} //SuffixImpl
