/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.miniJava.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.tetrabox.miniJava.MiniJavaPackage;
import org.tetrabox.miniJava.VariableDeclarator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variable Declarator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VariableDeclaratorImpl extends MinimalEObjectImpl.Container implements VariableDeclarator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VariableDeclaratorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MiniJavaPackage.Literals.VARIABLE_DECLARATOR;
  }

} //VariableDeclaratorImpl
